- name: httpd
  hosts: docker.node1
  tasks:
    - name: Execute Current date and time.
      command: date
    - name: Execute yum update to install httpd
      command: yum update all -y
    - name: Remove httpd and to test.
      yum:
        name: httpd
        autoremove: yes
        state: absent
#    - name: Execute httpd to install
#      yum:
#        name: httpd
#        state: present
#    - name: Start httpd service to run httpd
#      service:
#        name: httpd
#        state: started

